// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMtaKk99mf4OOLAfZkc5XS93tG5WTtfg',
    appId: '1:886188337372:web:7c3f9866989bb206836c19',
    messagingSenderId: '886188337372',
    projectId: 'pantryreadyhub',
    authDomain: 'pantryreadyhub.firebaseapp.com',
    storageBucket: 'pantryreadyhub.firebasestorage.app',
    measurementId: 'G-CB1TCEN4C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZMhKWnHyGz3TTJZ_0psY5aJlNymJJ7Y',
    appId: '1:886188337372:android:8ecf5b5d27ef9f1b836c19',
    messagingSenderId: '886188337372',
    projectId: 'pantryreadyhub',
    storageBucket: 'pantryreadyhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXXn6TaIQP-KAIw9ivCNyl8JfoveX6s8s',
    appId: '1:886188337372:ios:28086070743714b9836c19',
    messagingSenderId: '886188337372',
    projectId: 'pantryreadyhub',
    storageBucket: 'pantryreadyhub.firebasestorage.app',
    iosBundleId: 'com.example.pantryready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXXn6TaIQP-KAIw9ivCNyl8JfoveX6s8s',
    appId: '1:886188337372:ios:28086070743714b9836c19',
    messagingSenderId: '886188337372',
    projectId: 'pantryreadyhub',
    storageBucket: 'pantryreadyhub.firebasestorage.app',
    iosBundleId: 'com.example.pantryready',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMtaKk99mf4OOLAfZkc5XS93tG5WTtfg',
    appId: '1:886188337372:web:203429e41fb284e3836c19',
    messagingSenderId: '886188337372',
    projectId: 'pantryreadyhub',
    authDomain: 'pantryreadyhub.firebaseapp.com',
    storageBucket: 'pantryreadyhub.firebasestorage.app',
    measurementId: 'G-5WD67N9QTF',
  );
}
